[package]
name = "raytracing"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "0.30.10"
itertools = "0.14.0"
num-complex = "0.4.6"
rand = "0.9.2"
rayon = "1.11.0"
softbuffer = "0.4.8"
tobj = "4.0.3"
winit = "0.30.12"

[profile.release]
debug = true
